jellyfin_ports:
  - "8096:8096"
  - "8920:8920" #optional
  - "7359:7359/udp" #optional
  - "1900:1900/udp" #optional

jellyfin_volumes:
  - "{{ docker_dir }}/jellyfin:/config"
  - "{{ raid_dir }}/media/tv:/data/tvshows"
  - "{{ raid_dir }}/media/movies:/data/movies"
  - "{{ raid_dir }}/media/music:/data/music"
  - "{{ raid_dir }}/media/youtube-music:/data/youtube-music"