---
- name: SSH Port Juggle | Try connecting via SSH using the configured port from geerlingguy.security
  wait_for_connection:
    timeout: 5
  vars:
    ansible_ssh_port: "{{ security_ssh_port }}"
  register: _ssh_port_security_result
  ignore_errors: true

- name: SSH Port Juggle | Log the port being used (custom)
  debug:
    msg: "Trying to connect using port {{ security_ssh_port }} (custom from security_ssh_port)"
  when: _ssh_port_security_result is not failed

- name: Set the ansible_ssh_port fact to the custom port
  set_fact:
    ansible_ssh_port: "{{ security_ssh_port }}"
  when: _ssh_port_security_result is not failed

- name: SSH Port Juggle | Set the ansible_ssh_port to the fallback default port (22)
  set_fact:
    ansible_ssh_port: "22"
  when: _ssh_port_security_result is failed

- name: SSH Port Juggle | Log the port being used (fallback to 22)
  debug:
    msg: "Custom port connection failed. Trying to connect using port 22 (fallback)."
  when: _ssh_port_security_result is failed

- name: SSH Port Juggle | Try connecting again using the fallback port 22
  wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_default_result
  when: _ssh_port_security_result is failed

- name: SSH Port Juggle | Fail if neither port works
  fail: msg="Neither the configured ansible_port {{ security_ssh_port }} nor the fallback port 22 were reachable."
  when:
    - _ssh_port_security_result is failed
    - _ssh_port_default_result is failed
