version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    {% if not app_cidr == "" %}
    networks:
      app:
        ipv4_address: {{ app_base }}.18
    {% else %}
    ports:
      - "8123:8123"
    {% endif %}
    restart: always
    volumes:
      - "{{ docker_dir }}/homeassistant:/config"
    environment:
      - TZ={{ timezone }}
