---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
{% for volume in jellyfin_volumes %}
      - "{{ volume }}"
{% endfor %}
    ports:
{% for port in jellyfin_ports %}
      - "{{ port }}"
{% endfor %}
    restart: unless-stopped
