---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
{% for volume in lidarr_volumes %}
      - "{{ volume }}"
{% endfor %}
    ports:
{% for port in lidarr_ports %}
      - "{{ port }}"
{% endfor %}
    restart: unless-stopped
