# templates/monitoring.yml

version: '3'

services:
  monitoring-node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  monitoring-prometheus:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus
    user: "{{ guid }}:{{ guid }}"
    ports:
      - "{{ monitoring_prometheus_ports[0] }}"
    volumes:
      - "{{ monitoring_prometheus_volumes[0] }}"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  monitoring-grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    user: "{{ guid }}:{{ guid }}"
    ports:
      - "{{ monitoring_grafana_ports[0] }}"
    volumes:
      - "{{ monitoring_grafana_volumes[0] }}"
    environment:
      - GF_SECURITY_ADMIN_USER={{ monitoring_grafana_admin_user }}
      - GF_SECURITY_ADMIN_PASSWORD={{ monitoring_grafana_admin_password }}
    restart: unless-stopped

configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'node_exporter'
          static_configs:
            - targets: ['host.docker.internal:9100']
