version: '3'
services:
  nginxproxymanager:
    container_name: nginxproxymanager
    image: jc21/nginx-proxy-manager:{{ nginxproxymanager_version }}
    {% if not app_cidr == "" %}
    networks:
      app:
        ipv4_address: {{ app_base }}.24
    {% else %}
    ports: "{{ nginxproxymanager_ports }}"
    {% endif %}
    restart: always
    volumes: "{{ nginxproxymanager_volumes }}"
