---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
{% for port in prowlarr_ports %}
      - "{{ port }}"
{% endfor %}
    volumes:
{% for volume in prowlarr_volumes %}
      - "{{ volume }}"
{% endfor %}

    restart: unless-stopped
