---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
{% for port in radarr_ports %}
      - "{{ port }}"
{% endfor %}
    volumes:
{% for volume in radarr_volumes %}
      - "{{ volume }}"
{% endfor %}
    restart: unless-stopped
