---
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
{% for volume in readarr_volumes %}
      - "{{ volume }}"
{% endfor %}
    ports:
{% for port in readarr_ports %}
      - "{{ port }}"
{% endfor %}
    restart: unless-stopped
