version: '3.8'
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{ timezone }}
    volumes:
{% for volume in sonarr_volumes %}
      - "{{ volume }}"
{% endfor %}
    ports:
{% for port in sonarr_ports %}
      - "{{ port }}"
{% endfor %}
    restart: unless-stopped
