version: '3'
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: "{{ inventory_hostname }}"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
{% for port in syncthing_ports %}
      - "{{ port }}"
{% endfor %}
    volumes:
{% for volume in syncthing_volumes %}
      - "{{ volume }}"
{% endfor %}
    restart: unless-stopped
