---
- name: Install Python and python3-pip
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install docker module for Python
  pip:
    name:
      - docker
      - docker-compose

- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"

- name: Include variables for each service
  include_vars: "{{ item }}"
  loop: "{{ services }}"
  when: lookup('file', item + '.yml') is not none
  vars:
    item: "group_vars/{{ item }}.yml"

- name: Deploy services using individual compose files
  template:
    src: "templates/{{ item }}.yml"
    dest: "{{ docker_compose_dir }}/{{ item }}.yml"
  loop: "{{ services }}"
  loop_control:
    label: "{{ item }}"

- name: Docker-compose up for each service
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
    files: "{{ item }}.yml"
  loop: "{{ services }}"
  loop_control:
    label: "{{ item }}"
